/* A plan is a personal commitment. Quiz scores never complete tasks automatically. */
(() => {
  'use strict';
  const $ = selector => document.querySelector(selector);
  const node = (tag, text, className) => { const n=document.createElement(tag); if(text!==undefined)n.textContent=String(text); if(className)n.className=className; return n; };
  const topics={java:'Java 基础',concurrency:'并发与 JVM',spring:'Spring 与 HTTP',data:'数据库 / Redis / MQ',project:'Agent 项目',algorithm:'算法思路'};
  const state={token:'',items:[],materials:[],allDates:false,busy:false,editing:null,preview:null,revision:0,timer:null};
  const localDate = (date=new Date()) => { const offset=date.getTimezoneOffset()*60000; return new Date(date.getTime()-offset).toISOString().slice(0,10); };
  const dayLabel = value => { const date=new Date(value+'T12:00:00'); return Number.isNaN(date.getTime())?value:date.toLocaleDateString('zh-CN',{month:'long',day:'numeric',weekday:'long'}); };
  const status = (text='') => { $('#planStatus').textContent=text; };
  async function api(path,body,method='POST') { const response=await fetch(path,{credentials:'same-origin',method:body===undefined?'GET':method,headers:{'X-Archive-Token':state.token,...(body===undefined?{}:{'Content-Type':'application/json'})},...(body===undefined?{}:{body:JSON.stringify(body)})});let data;try{data=await response.json();}catch(_){throw Error('本机服务返回异常，请重试。');}if(!response.ok)throw Error(data.error||'操作没有完成。');return data; }
  function taskLink(task,kind) { const params=new URLSearchParams({task:task.id});if(kind==='read'){if(task.material_id)params.set('material',task.material_id);return 'index.html?'+params;}if(task.topic)params.set('topic',task.topic);if(task.material_id)params.set('material',task.material_id);return 'interview.html?'+params; }
  function taskRow(task) {
    const row=node('article',undefined,'plan-task'+(task.completed?' is-complete':''));row.dataset.taskId=task.id;
    const toggle=node('button',task.completed?'✓':'○','task-check');toggle.type='button';toggle.dataset.taskComplete='';toggle.dataset.action=task.completed?'restore':'complete';toggle.setAttribute('aria-label',(task.completed?'恢复任务：':'完成任务：')+task.title);toggle.setAttribute('aria-pressed',String(task.completed));toggle.addEventListener('click',()=>changeCompletion(task,toggle));
    const body=node('div',undefined,'task-body');const heading=node('div',undefined,'task-heading');heading.append(node('h3',task.title),node('span',task.completed?'已完成':'待完成','task-state'));body.append(heading);
    const meta=[topics[task.topic]||'自主学习','预计 '+task.estimated_minutes+' 分钟'];if(task.actual_minutes)meta.push('实际 '+task.actual_minutes+' 分钟');if(task.material_id){const m=state.materials.find(item=>item.id===task.material_id);meta.push(task.material_available===false?'关联资料暂不可用':m?.title||'已关联资料');}body.append(node('p',meta.join(' · '),'task-meta'));
    if(task.notes){const details=node('details',undefined,'task-notes');details.append(node('summary','目标与验收'),node('p',task.notes));body.append(details);}
    const actions=node('div',undefined,'task-actions');const read=node('a',task.material_id?'阅读资料 ↗':'选择资料 ↗','button button-quiet');read.href=taskLink(task,'read');read.dataset.action='read';read.dataset.taskRead='';const practice=node('a','练习本任务 ↗','button button-quiet');practice.href=taskLink(task,'practice');practice.dataset.action='practice';practice.dataset.taskPractice='';
    if(task.material_available===false){for(const link of [read,practice]){link.setAttribute('aria-disabled','true');link.removeAttribute('href');link.title='请先从资料回收站恢复关联资料。';}body.append(node('p','请先恢复关联资料，再阅读或练习。','field-help'));}
    const edit=node('button','编辑任务','button button-quiet');edit.type='button';edit.dataset.action='edit';edit.dataset.taskEdit='';edit.addEventListener('click',()=>openTask(task));actions.append(read,practice,edit);body.append(actions);
    const quiz=task.quiz||{};if(quiz.sessions){const record=node('p',`关联 ${quiz.sessions} 轮练习 · 已交卷 ${quiz.finished||0} 轮${quiz.total?' · 首答 '+quiz.correct+'/'+quiz.total+' 题':''}。任务仍需你确认完成。`,'task-practice');body.append(record);}
    row.append(toggle,body);return row;
  }
  function render() {
    const list=$('#planTaskList');list.replaceChildren();$('#planEmpty').hidden=state.items.length>0;
    let previous='';for(const task of state.items){if(state.allDates&&task.date!==previous){list.append(node('h2',dayLabel(task.date),'task-day-heading'));previous=task.date;}list.append(taskRow(task));}
    const focus=new URL(location.href).searchParams.get('task');if(focus){const row=[...list.querySelectorAll('[data-task-id]')].find(item=>item.dataset.taskId===focus);if(row){row.classList.add('is-highlighted');row.scrollIntoView({block:'nearest',behavior:'auto'});}}
  }
  function overview(summary) { $('#planProgress').textContent=(summary.completed||0)+' / '+(summary.total||0);$('#planTimeStat').textContent=(summary.planned_minutes||0)+' / '+(summary.actual_minutes||0)+' 分钟';$('#planPracticeStat').textContent=(summary.quiz?.sessions||0)+' 轮'; }
  async function load() {
    const revision=++state.revision;const params=new URLSearchParams({status:$('#planStatusFilter').value,search:$('#planSearch').value.trim()});if(!state.allDates)params.set('date',$('#planDate').value);
    const [tasks,summary]=await Promise.all([api('/api/planning/tasks?'+params),api('/api/planning/summary?date='+encodeURIComponent($('#planDate').value))]);if(revision!==state.revision)return;state.items=tasks.items||[];overview(summary);render();$('#planTaskList').dataset.ready='true';
  }
  async function changeCompletion(task,button) { if(state.busy)return;state.busy=true;button.disabled=true;status();try{await api('/api/planning/tasks/'+encodeURIComponent(task.id),{completed:!task.completed},'PATCH');await load();status(task.completed?'任务已恢复为待完成。':'已确认完成。练习结果与学习掌握程度仍需分别核对。');}catch(error){status(error.message);}finally{state.busy=false;button.disabled=false;} }
  async function loadMaterials() { const data=await api('/api/materials');state.materials=data.items||[];const select=$('#taskMaterial');select.replaceChildren();const empty=node('option','暂不绑定资料');empty.value='';select.append(empty);for(const item of state.materials){const option=node('option',item.title);option.value=item.id;select.append(option);} }
  function openTask(task=null) {
    if(state.busy)return;state.editing=task;$('#taskForm').reset();$('#taskDialogTitle').textContent=task?'编辑学习任务':'添加学习任务';$('#taskTitle').value=task?.title||'';$('#taskDate').value=task?.date||$('#planDate').value;$('#taskMinutes').value=task?.estimated_minutes??45;$('#taskActualMinutes').value=task?.actual_minutes??0;$('#taskTopic').value=task?.topic||'';$('#taskNotes').value=task?.notes||'';
    if(task?.material_id&&!state.materials.some(item=>item.id===task.material_id)){const option=node('option','原关联资料（暂不可用）');option.value=task.material_id;$('#taskMaterial').append(option);}$('#taskMaterial').value=task?.material_id||'';
    const locked=Boolean(task?.quiz?.sessions);$('#taskTopic').disabled=locked;$('#taskMaterial').disabled=locked;$('#taskAssociationNotice').hidden=!locked;$('#taskActualLabel').hidden=!task;$('#taskFormStatus').textContent='';$('#taskDialog').showModal();$('#taskTitle').focus();
  }
  async function saveTask(event) { event.preventDefault();if(state.busy)return;state.busy=true;$('#taskSave').disabled=true;$('#taskFormStatus').textContent='正在保存…';const editing=state.editing;const body={date:$('#taskDate').value,title:$('#taskTitle').value.trim(),topic:$('#taskTopic').value,material_id:$('#taskMaterial').value,notes:$('#taskNotes').value,estimated_minutes:Number($('#taskMinutes').value),actual_minutes:editing?Number($('#taskActualMinutes').value):0};if(editing?.quiz?.sessions){delete body.topic;delete body.material_id;}try{await api('/api/planning/tasks'+(editing?'/'+encodeURIComponent(editing.id):''),body,editing?'PATCH':'POST');$('#taskDialog').close();$('#planDate').value=body.date;state.allDates=false;$('#planAllDates').setAttribute('aria-pressed','false');await load();status(editing?'任务已保存。':'任务已添加。可以阅读资料，再开始练习。');}catch(error){$('#taskFormStatus').textContent=error.message;}finally{state.busy=false;$('#taskSave').disabled=false;} }
  function clearPreview() { state.preview=null;$('#planImportPreviewPanel').hidden=true;$('#planImportConsent').checked=false;$('#planImportSubmit').disabled=true; }
  function preview() { clearPreview();$('#planImportStatus').textContent='';try{const data=JSON.parse($('#planImportText').value);if(!data||Array.isArray(data)||data.schema!=='shizhi-plan-v1'||!Array.isArray(data.tasks)||data.tasks.length<1||data.tasks.length>100)throw Error('请使用 shizhi-plan-v1 格式，并包含 1–100 个任务。');const ids=new Set();for(const task of data.tasks){if(!task||!task.id||!task.title||!/^\d{4}-\d{2}-\d{2}$/.test(task.date||''))throw Error('每项任务需要稳定 ID、真实日期和标题。');if(ids.has(task.id))throw Error('同一份计划中不能有重复任务 ID。');ids.add(task.id);}state.preview=data;$('#planImportCount').textContent=data.tasks.length+' 项任务 · '+new Set(data.tasks.map(task=>task.date)).size+' 天';$('#planImportItems').replaceChildren(...data.tasks.map(task=>{const item=node('li');item.append(node('strong',task.date+' · '+task.title),node('span',(topics[task.topic]||'自主学习')+' · 预计 '+(task.estimated_minutes??0)+' 分钟'));return item;}));$('#planImportPreviewPanel').hidden=false;$('#planImportStatus').textContent='预览不会写入数据；确认时服务会再次验证完整格式与资料关联。';}catch(error){$('#planImportStatus').textContent=error instanceof SyntaxError?'JSON 格式不正确，请只粘贴 JSON，不要包含代码围栏。':error.message;} }
  async function importPlan() { if(state.busy||!state.preview||!$('#planImportConsent').checked)return;const accepted=state.preview;state.busy=true;$('#planImportSubmit').disabled=true;$('#planImportStatus').textContent='正在验证并导入…';try{const data=await api('/api/planning/import',{...accepted,confirmed:true});$('#planImportDialog').close();$('#planDate').value=accepted.tasks[0].date;state.allDates=true;$('#planAllDates').setAttribute('aria-pressed','true');await load();status('计划已导入。'+(data.skipped?' '+data.skipped+' 个已有任务已跳过，进度保留。':''));}catch(error){$('#planImportStatus').textContent=error.message;}finally{state.busy=false;$('#planImportSubmit').disabled=!$('#planImportConsent').checked||!state.preview;} }
  function dateChanged() { if(!$('#planDate').value)return;state.allDates=false;$('#planAllDates').setAttribute('aria-pressed','false');status();load().catch(error=>status(error.message)); }
  function moveDate(delta) { const day=new Date($('#planDate').value+'T12:00:00');day.setDate(day.getDate()+delta);$('#planDate').value=localDate(day);dateChanged(); }
  async function mount() {
    $('#planDate').value=localDate();$('#planFilters').open=!matchMedia('(max-width: 760px)').matches;$('#planAddOpen').addEventListener('click',()=>openTask());$('#planEmptyAdd').addEventListener('click',()=>openTask());$('#taskForm').addEventListener('submit',saveTask);document.querySelectorAll('[data-task-close]').forEach(button=>button.addEventListener('click',()=>{if(!state.busy)$('#taskDialog').close();}));$('#taskDialog').addEventListener('cancel',event=>{if(state.busy)event.preventDefault();});
    $('#planDate').addEventListener('change',dateChanged);$('#planPrevDay').addEventListener('click',()=>moveDate(-1));$('#planNextDay').addEventListener('click',()=>moveDate(1));$('#planToday').addEventListener('click',()=>{$('#planDate').value=localDate();dateChanged();});$('#planAllDates').addEventListener('click',()=>{state.allDates=!state.allDates;$('#planAllDates').setAttribute('aria-pressed',String(state.allDates));load().catch(error=>status(error.message));});$('#planStatusFilter').addEventListener('change',()=>load().catch(error=>status(error.message)));$('#planSearch').addEventListener('input',()=>{clearTimeout(state.timer);state.timer=setTimeout(()=>load().catch(error=>status(error.message)),200);});
    $('#planImportOpen').addEventListener('click',()=>{if(state.busy)return;clearPreview();$('#planImportStatus').textContent='';$('#planImportDialog').showModal();});document.querySelectorAll('[data-plan-import-close]').forEach(button=>button.addEventListener('click',()=>{if(!state.busy)$('#planImportDialog').close();}));$('#planImportDialog').addEventListener('cancel',event=>{if(state.busy)event.preventDefault();});$('#planImportPreview').addEventListener('click',preview);$('#planImportText').addEventListener('input',clearPreview);$('#planImportConsent').addEventListener('change',()=>{$('#planImportSubmit').disabled=!$('#planImportConsent').checked||!state.preview||state.busy;});$('#planImportSubmit').addEventListener('click',importPlan);$('#planImportFile').addEventListener('change',async()=>{clearPreview();const file=$('#planImportFile').files[0];if(!file)return;if(file.size>1024*1024){$('#planImportStatus').textContent='计划 JSON 不能超过 1 MB。';return;}try{$('#planImportText').value=await file.text();preview();}catch(_){$('#planImportStatus').textContent='文件读取失败，请重新选择。';}});
    if(location.protocol==='file:'){status('请先启动拾知本地服务。直接双击 HTML 不能保存计划。');$('#planAddOpen').disabled=true;$('#planEmptyAdd').disabled=true;$('#planImportOpen').disabled=true;return;}
    try{state.token=(await api('/api/bootstrap')).token;await loadMaterials();const params=new URL(location.href).searchParams;const date=params.get('date');if(/^\d{4}-\d{2}-\d{2}$/.test(date||''))$('#planDate').value=date;else if(params.get('task')){const task=await api('/api/planning/tasks/'+encodeURIComponent(params.get('task')));$('#planDate').value=task.date;}await load();}catch(error){status(error.message);}
  }
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount,{once:true});else mount();
})();
